[package]
name = "fut"
version = "0.1.2"
description = "simple file util crate"
license = "MIT"
repository = "https://github.com/selfup/fut"
authors = ["selfup <boudinot.regis@yahoo.com>"]

[dependencies]
