[package]
name = "fut"
version = "0.1.3"
description = "simple file util crate"
license = "MIT"
repository = "https://github.com/selfup/fut"
authors = ["selfup <boudinot.regis@yahoo.com>"]
readme = "README.md"

[dependencies]
